### ISSUE TITLE
Checklist para revisar el paquete

### ISSUE THREAD

**Issue by yabellini** [BMilesRouillon/weatherdata#2]
A lo largo de las secciones los ejercicios transversales que llamamos "Construyendo un paquete de R paso a paso" son una guía para, justamente, construir un paquete que lee y ayuda a analizar datos meteorológicos. 

A continuación encontrarás una lista de elementos que debe tener o con los que debe cumplir el paquete para estar completo. 

- [x] Estructura del paquete
- [x] Repositorio local
- [x] Repositorio remoto

## DESCRIPTION

- [x] Título
- [x] Descripción
- [x] Las personas involucradas estan listadas en Auth@rs

## Funciones y datos

- [x] (al menos) 3 funciones
- [x] (al menos) 1 set de datos

## Documentación

- [x] Todas las funciones y datos están documentados
- [x] README completo
- [x] Incluye una viñeta que explica como usar las funciones
- [x] El paquete tiene una página web

## Tests

- [x] El paquete tiene tests que cubren al menos el 75% del código de las funciones
- [x] El paquete tiene una GitHub action que revisa la covertura de los tests
- [x] El paquete pasa R CMD checks
- [x] El paquete tiene una GitHub action que chequea el paquete en distintos sistemas operativos

## Otros

- [x] Incluye una licencia
- [x] El README incluye instrucciones sobre:
  - [x] como instalar el paquete.
  - [x] los autores. 
  - [x] como se puede contribuir al paquete.
